FROM python:3.7-slim

RUN mkdir -p /app
WORKDIR /app

RUN apt-get update 

RUN apt-get install -y \
    python3-openslide \
    libjpeg-dev \
    zlib1g-dev \
    libvips \
    libvips-tools \
    gcc
    
RUN curl -s https://packagecloud.io/install/repositories/cytomine-uliege/Cytomine-python-client/script.python.sh | bash
    
COPY . /app

RUN pip install torch==2.0.1+cpu torchvision==0.15.2+cpu -f https://download.pytorch.org/whl/torch_stable.html
RUN pip install -r requirements_3.txt


ENTRYPOINT ["python","/app/app.py"]
